### ISSUE TITLE
Refined UI design to support Split Tunnel feature

### ISSUE THREAD

**Issue by jess-cook03** [mozilla-mobile/mozilla-vpn-client#1164]
Per requirements gathering and conversations the design needs have been identified:

Current settings page treatment has a two list pattern for 'protected' and 'unprotected' apps... thinking through this two lists and the interaction that is currently happening.... doesn't seem like the best practice. Instead after chatting with @lesleyjanenorton .... and looking at some competitor treatments... one list with bulk action checkboxes makes the most sense.

When the spec is ready we will need content support from @chrisrooneys 

- [x] toggle interaction.... should actually be reversed (toggle off to manually manage the app list) so default state should actually be on. (currently its off) wording is confusing here

- [x] change current UI to one list with bulk action check boxes

- [x] work on better language to communication the interaction to users (btw info icon and then toggle on/off state).. help them understand apps that are selected are 'protected' apps that aren't selected are not. And that by default all apps are protected unless toggle it off to manage them individually.

- [x] Nice to have: possible search bar inside the app list

**Comment by oskirby** [comment]
Just to throw my two cents into the discussion. I dislike that the current UI moves the application out from under you when you click it, since it goes into the other list, and I just find it a little disorienting when the thing I was interacting with disappears instead of displaying some kind of state change.

The application list is also enormously long for any system that has been around for any length of time, so it can quickly become difficult to find things. This is made even worse when the applications in question move around on you as they change from 'protected' to 'unprotected'

Some nice-to-have features based on my experience implementing this on Linux:
- The default traffic routing policy is for all traffic to go through the VPN unless specifically excluded, it would be nice to have the option to invert this policy so that all traffic goes through the local network unless specifically included.
- On Linux at least, we can change the states of the applications while connected.
- Some status to show which applications are actually running (or maybe show them at the top of the list) would make it easier to find the application you're trying to change state on.
- Applications can actually be in one of three states in the backend, it would be nice to access them all via the UI. These states are:
  - `active` which corresponds to the 'protected' state in the UI, this is the default state and all traffic goes through the VPN.
  - `excluded` which corresponds to the 'unprotected' state in the UI, where all traffic is routed over the user's local network and the application cannot access the VPN.
  - `blocked` which has no corresponding connection to the UI where all traffic from this application is blocked from reaching any network interface.It would be nice to enable this state somehow (See #908)

**Comment by jess-cook03** [comment]
@oskirby thank you for all of this context! This is super helpful and we will review your considerations!!!

Question: I would like to understand more on why we would want to switch the default from the current treatment? Am I understanding your suggestion here correctly? Which is: do not make all apps protected on default, instead make them unprotected and then have users manually protect the ones they want instead? If it is the later... I am not sure if we would want to put that much on the user... users get VPN for the protection and piece of mind and most folks have the 'set it and forget it' mentality when it comes to S&P that I am not sure if leaving this as a manual setting by default is the right approach.

I agree and hear you on the disorienting interaction of the two lists and items jumping around.... this is what lead to the one list - bulk action potential solution... we will be working through a UI spec and explorations around this and post for feedback when ready :)

My perspective:
To a user the key pieces to them are 1) what is the default functionality (toggle) and then 2) providing them a way to manually change from that default if they want to (app list management).
Focusing our UI on those two pieces.
Over designing this interaction with added layers will cause confusion... that is my hypothesis based on the current treatment.

I understand that the application list can be very long for some users... we can think more about how to address that potentially with a search bar or something we could try in the future. But that is more of a nice to have IMO..

I say that because with this setting/feature I have a few questions about users actual behavior here with this.... do people actively use this? do they even know what it means? Perhaps we can get some data on this for the future once this gets implemented cross-platform.

**Comment by oskirby** [comment]
For my suggestion regarding the default treatment, I see there being a use case in which a user isn't really interested in protecting their network traffic (eg: they might be on their home network with strong WiFi credentials) but they have one pesky application that they don't want to access their local network or want to change their geographic location. For example, they might just want to use a foreign streaming service without messing with the rest of their network.

To be clear, I don't think we should change the default behaviour.

**Comment by peterbenvenuto** [comment]
Designs have been approved and delivered to engineering for current implementation.

**Comment by lesleyjanenorton** [comment]
Closing as fixed/done/delivered
