### ISSUE TITLE
Data collection and use option is displayed for each sign in

### ISSUE THREAD

**Issue by mariaberlinger** [mozilla-mobile/mozilla-vpn-client#1241]
#### VPN version:
- 2.3.2 (2.202106231536);

#### Affected Platforms:
- Windows 10x64;
- macOS 11.14

#### Prerequisites:
- Have Mozilla VPN installed;
- Have one FxA account with subscription;

#### Steps to reproduce:

1. Open the vpn app and click the Get started button;
2. Click one of the options for the Data collection and complete the sign in with the account from prerequisites;
4. Log out;
5. Go to log in again;

#### Expected result:
- Based on the option chosen at step 1 the Data collection and use isn’t displayed again.

#### Actual result:
- The app doesn’t count the chosen option and asks you every time you log in again no matter what option you choose.

#### Notes:
- See the attached screen record;
![vpn](https://user-images.githubusercontent.com/54393305/123389759-e2b71680-d5a2-11eb-9cff-6605ea963cef.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-634)

**Comment by bakulf** [comment]
The app resets the telemetry-policy choice during the logout because this is currently considered as part of the user settings. I wonder if we want to have a better UX. @jess-cook03 what do you think?
There are a few pros/cons in showing the telemetry policy view only once. Consider the following points:

- the user cannot see the view again.
- after a new login, the user "inherits" the same telemetry-policy choice.

@jess-cook03 can you help us here?

**Comment by jess-cook03** [comment]
@bakulf 
Yes! We will take a look at this today.
cc @peterbenvenuto

**Comment by jess-cook03** [comment]
@bakulf are we able to only show it once? From UX perspective showing it to the same user each time they logout/in that becomes redundant --- especially since they can go to the settings anytime and change this.
We would like to have the user set it and then have it inherit the same opt in or out that they chose the first time they interact with it.
Hopefully that makes sense -- let me know if not! 
Would this be a change we could get into v2.5?
Thanks!
cc @peterbenvenuto

**Comment by data-sync-user** [comment]
➤ Jessica Cook commented:

Andrea Marchesini can I assign this to you if we plan to implement this change for 2.5?

**Comment by bakulf** [comment]
Closed by #1054

**Comment by data-sync-user** [comment]
➤ Maria Berlinger commented:

Hello,
I've tried to verify this issue but now it seems that the telemetry screen doesn't show at all.
I've deleted my cache from Mozilla VPN and nothing.
It is something else that should be done to trigger it?

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Yes, you can use the inspector and call reset. This will reset the telemetry policy too.

**Comment by data-sync-user** [comment]
➤ Maria Berlinger commented:

Hello,
This is verified as fixed using Mozilla VPN 2.5.0 (2.202109111821) and 2.6.0 (2.202109191916) on Windows 10 and  2.6.0 (2.202109201913) on MacOS Big Sur 11.6.
