### ISSUE TITLE
The Required Update screen gets stuck

### ISSUE THREAD

**Issue by mariaberlinger** [mozilla-mobile/mozilla-vpn-client#1253]
#### VPN version:
- 2.3.2 (2.202106231537);

#### Affected Platforms:
- Windows 10x64;

#### Steps to reproduce:

1. Access http://localhost:8766/ 
2. Enter force_update_check 1 command
3. The Update Required screen is displayed
4. Click the update button

#### Expected result:
- The app is updated and the screen is dismissed

#### Actual result:
- The Update Required screen is still displayed

**Comment by bakulf** [comment]
Can you please share the logs? I suspect the app is unable to fetch the MSI from balrog/guardian-website

**Comment by mariaberlinger** [comment]
[mozillavpn-2021-7-6_3.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6770643/mozillavpn-2021-7-6_3.txt)

**Comment by oskirby** [comment]
So, it seems that the upgrade was rejected because it would have triggered a downgrade from 2.3.2 down to 2.2.0, which is something that the WIX installer explicitly disallows. As a quick fix, we should probably get the staging site updated with a more modern release.

When checking the logs, we find that the client checks for the latest version from the URL: https://stage.balrog.nonprod.cloudops.mozgcp.net/json/1/FirefoxVPN/1/WINNT_x86_64/release-cdntest/update.json

Which, at the time of writing, returns the following content:
```
{
  "version": "2.2.0",
  "url": "https://stage.guardian.nonprod.cloudops.mozgcp.net/downloads/vpn/windows/v2.2.0/MozillaVPN.msi",
  "required": true,
  "hashFunction": "sha512",
  "hashValue": "d8f42281fd62cf749582116987298b43d9032544a9b324501547440ae4b6ddd4881ef4d8a5a4e3a599a523e6183787e62620e6319f4f34e5809c97aefb8ad6c5"
}
```

However, there is probably some room for improvement by handling errors better.

**Comment by rbillings** [comment]
This is likely a staging issue. We need a newer version of the VPN as the recommended version.

**Comment by birdsarah** [comment]
@bakulf has sent a message to @MihaiTabara to resolve this.

**Comment by MihaiTabara** [comment]
> @bakulf has sent a message to @MihaiTabara to resolve this.

where? FTR, I didn't get anything yet.

**Comment by MihaiTabara** [comment]
> This is likely a staging issue. We need a newer version of the VPN as the recommended version.

which version do we need? Happy to adjust Balrog staging to reflect that

**Comment by rbillings** [comment]
We're going to close this for now and discuss with Mihai about future staging env.
