### ISSUE TITLE
UX/UI for multi-hop feature

### ISSUE THREAD

**Issue by jess-cook03** [mozilla-mobile/mozilla-vpn-client#1310]
v2.5 major feature

**Goal**
Multi-Hop VPN is a feature that uses multiple VPN servers instead of one. This VPN server chaining method gives extra security and privacy.  The most common multi-hop VPN is a Double VPN, which uses two VPN servers and thus has double encryption and extra security for your IP address. 

**P1**
Timeline based on a sprints

* First round feedback: July 19-20th
* Sprint 1 design delivery: July 23rd
* Second round feedback: July 26-27th
* Sprint 2 design delivery: July 30th
* Finalization bumper period (for feedback, last changes): July 30th - Aug 4th
* Design + content freeze: August 4th

**Linked issues (if applicable)**
Please list any other GitHub issues that are constrained by or dependent on this feature here:

* #1041 

**Additional context**
Add any resources, documents, or relevant links for context here:

* Figma file: [https://www.figma.com/file/3ro5ivHWvcQZFbRWGQbUoS/Multi-Hop-Feature](https://www.figma.com/file/3ro5ivHWvcQZFbRWGQbUoS/Multi-Hop-Feature|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-713)

**Comment by oskirby** [comment]
I can think of the following UI elements that would help enable the multihop feature:

1. A checkbox under network settings to enable/disable the multihop feature. By default this should be disabled since it's not likely to be needed for most users and comes with a performance penalty.
2. The current server selection UI may want to be reworded to reflect that is the location that the user's traffic will appear from. A technical name for this might be something along the lines of "exit node", "final hop", or "egress server".
3. Add another server selection UI to allow the users to select the location that an eavesdropper would see their traffic go to. We could call this something like the "first hop", or the "ingress server". This UI element could be optional since it may be acceptable to let the VPN client pick this at random.
4. For exceptional use cases, maybe a slider or something to select how many hops the user desires. Though I have a hard time seeing a need for anything more than 2 hops.

**Comment by jess-cook03** [comment]
@oskirby thank you for these insights!! cc @peterbenvenuto

**Comment by peterbenvenuto** [comment]
@oskirby Thank you! Working on that feature now, I appreciate the insights!

**Comment by data-sync-user** [comment]
➤ Peter Benvenuto commented:

Final designs are completed and can be found in this figma file ( https://www.figma.com/file/3ro5ivHWvcQZFbRWGQbUoS/Multi-Hop-Feature?node-id=286%3A10518 )

CC Brian Yee Lesley Norton
