### ISSUE TITLE
Replace the XMLHttpRequest object for glean with a `Task`

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#1405]
In this way we are 100% sure we don't try to send pings when the VPN is changing states. This should be easy to do exposing a `VPN.sendGleanPing(url, payload, headers)`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-780)

**Comment by oskirby** [comment]
Probably a good thing to tackle at the same time as #1262

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Beatriz Rizental Machado can we close this?

**Comment by data-sync-user** [comment]
➤ Beatriz Rizental Machado commented:

Huh, I missed this question. So, hm. Maybe we should not close this. The problem will persist after Glean migration… However I am not sure there is a problem at all. Glean will simply retry to send a ping when upload is unsuccesfull. It’s fine it upload fails because the VPN is changing states.

**Comment by data-sync-user** [comment]
➤ Beatriz Rizental Machado commented:

This is not an issue. Glean deals with upload errors and retries internally.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Moving back to Cancelled

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Moving back to Cancelled
