### ISSUE TITLE
rpmbuild does not work on Fedora 34

### ISSUE THREAD

**Issue by arnobl** [mozilla-mobile/mozilla-vpn-client#1466]
I followed the instructions provided in #450 and #1122 but `rpmbuild` fails.

I was able to build and run the app (thanks to https://github.com/mozilla-mobile/mozilla-vpn-client/issues/450#issuecomment-835496760).

Then I ran (based on #1122):
```
sudo dnf builddep linux/mozillavpn.spec
rpmbuild -bb linux/mozillavpn.spec
```
But it gives me as output this error message:
`Error: No source number 0`

I built the app based on commit 0ed5781.
Using an up-to-date Fedora 34.

┆Issue is synchronized with this [Jiraserver Bug](https://mozilla-hub.atlassian.net/browse/VPN-835)

**Comment by tbeckley** [comment]
Same here. At commit 242e86cfb0862be5f172214fca96f8227eb949b6. Latest fedora 34

**Comment by oskirby** [comment]
This bug was introduced in commit 92beeb927c79ae90b282ce83a8d2c63518dcea00 where we added the Github CI steps to automate the building of RPM packages for Fedora. Part of the way we got there is to use `./scripts/linux_script.sh` to produce the source tarball that the `mozillavpn.spec` is expecting to find as the `Source0`, and then apply some fixups to the `mozillavpn.spec` file so that version numbers will match up.

In the meantime, you can follow the build steps from our github workflow file for building RPM packages:
1. Produce the source tarball with `./scripts/linux_script.sh --source`. This should create files `.tmp/mozillavpn_<version>.orig.tar.gz` and `.tmp/mozillavpn.spec`
2. Run `rpmbuild -bb .tmp/mozillavpn.spec`

However, I should still fix this up by improving the documentation on how to build RPM packages, and to get the `.spec` file building again without needing to run `./scripts/linux_scrupt.sh`

**Comment by swatson555** [comment]
Running `rpmbuild -ba --build-in-place ./linux/mozillavpn.spec` at top level works fine for me.

**Comment by oskirby** [comment]
As an unofficial list of steps to build an RPM package from a git checkout:
1. `git clone` to fetch the mozilla-vpn-client project.
2. `git submodule init && git submodule update` to fetch the relevant submodules.
3. `pip3 install glean_parser==3.5 && ./scripts/generate_glean.py` to generate the telemetry code.
4. `sudo dnf builddep linux/mozillavpn.spec` to install the package build-dependencies.
5. `rpmbuild -ba linux/mozillavpn.spec` to build the package.

This is not yet a complete solution for official Fedora packages, since we still need a manual step to install `glean_parser`, which has no equivalent RPM package.

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Owen Kirby is there something the QA team needs to do on this issues or should we just close this?

Thank you.

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Luminita Buruian  I think we can close this issue, since we don’t officially support Fedora at this time.
