### ISSUE TITLE
Android IAP Edge Case 1 - User not signed into Play Store 

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#1528]
I get the impression that it would be unusual for a user to not be signed into the play store - especially as to get the app they need to be signed, but here goes.

Steps to reproduce (you can't really repro this as the feature is in development, this is for UX's benefit):
0. Be logged OUT of Play store on android
1. Open app on android
2. Login screen appears, sign in with an account that does not have a subscription

Expected:
3. Some kind of modal / display pops that tells the user they need to sign into Google Play

Actual:
3. The web view login screen will close and the user will just be left with the authenticating spinning wheel (because the play store cannot be queried for the subscription options if the user is signed out of the play store).

Engineering notes: 
1. Although it may be possible to create a button that opens the play store, I think just a text warning is okay as I believe it's very few users that will get into this state. They can hit "cancel" to stop the auth flow and then try again.
2. I also don't think it's worth checking for play store state before a user hits "get started" as they may already have a web subscription in which case they won't hit this edge case.

Other:
This actually might be an issue on iOS too that we haven't tested. @bakulf can you test this scenario on a test flight instance of iOS? I can't test it in prod until my subscription runs out.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-856)

**Comment by data-sync-user** [comment]
➤ Jessica Cook commented:

Sharing the UX documentation here for each edge case: https://www.figma.com/file/fXfxErqwSeqQzA65jcvwuZ/IAP-Android-iOS_Variable-Pricing?node-id=153%3A6740 ( https://www.figma.com/file/fXfxErqwSeqQzA65jcvwuZ/IAP-Android-iOS_Variable-Pricing?node-id=153%3A6740|smart-link )

**Comment by birdsarah** [comment]
The majority of this is done in #1541 except for a function that opens the play store.

**Comment by birdsarah** [comment]
Launch play store is done in commit 315083c

**Comment by birdsarah** [comment]
I used the built in error screen. Hitting "Sign Out" triggers a restart once the user has hopefully logged in. Unfortunately the "Sign Out" wording isn't ideal but didn't have another string.

I opted not to use a modal because there's state changing behind the scenes and it's messy.

<img src="https://user-images.githubusercontent.com/1796208/130343202-f3010967-1ee8-4a6b-ac74-a42364db611d.png" width=200/>

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

This has been verified as fixed on Mozilla VPN 2.5.0 (16303750) using an Android 9 Samsung Galaxy S10 Plus.

The user is presented with the below error screen:

!image-20210903-122708.png|width=400,height=854!

Steps further:

  1. Tap on the Go to Play Store button => the user is taken to Google Play Store
  2. Log into the google Play store => the user is successfully logged into the Google Play store
  3. Return to the VPN app and tap Sign Out => the user is taken to the welcome screen to restart the login process
  4. login with an existing FxA account => the user is successfully signed in, without Google Play error message 

Sarah Bird Please let us know if the above scenario is NOT the desired one. Otherwise, we can consider this issue fixed/closed.

Thank you

CC: Valentina Virlics

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Closing this as it has already been verified.

Thank you.
