### ISSUE TITLE
VPN remains in Connecting... state on Linux

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#1649]
**VPN version:**

* 2.5.0 (2.202108262125);

**Affected Platforms:**

* Linux Hirsute;

**Prerequisites:**

* Have one FxA account with subscription for Mozilla VPN;
* Have the VPN installed on your machine;

**Steps to reproduce:**
1. Open the VPN and activate Stage;
2. Sign in with the account from prerequisites;
3. Turn ON the VPN.

**Expected result:**

* VPN is turned on;

**Actual result:**

* VPN remains in “Connecting...” state

Attaching logs;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-911)

**Comment by oskirby** [comment]
Looking through the attached logs, it seems that the client reports a user agent of `MozillaVPN/2.5.0 (sys:ubuntu 21.04)` while the daemon has a version of `MozillaVPN/2.4.0 (sys:ubuntu 21.04)` so the underlying issue is that we have somehow upgraded the client without restarting the daemon.

Changes in the D-Bus API probably means that this mismatch is causing the `connected()` signal to get lost between the client and server, and therefore leaving the client hung in the `Connecting` state.

**Comment by oskirby** [comment]
I have been able to reproduce the issue as follows:
1. Install the mozillavpn from an older release (such as 2.5.1) using a `.deb` package.
2. Start the VPN and connect to something to ensure that the daemon is running.
3. Disconnect the VPN, which should leave the daemon running, but inactive.
4. Upgrade the VPN client using a 2.5.0 `.deb` package: `sudo dpkg -i mozillavpn_2.5.0-hirsute1_amd64.deb`
5. Re-start the VPN client and try to connect, which hangs forever because the daemon is still running version 2.4.1

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this on VPN 2.5.0 (2.202109031602) on Linux Focal using Owen’s steps and the issue is no longer reproducible.
