### ISSUE TITLE
“In-app support form” feature is not mentioned in the “What’s new” component

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#1658]
**VPN version:**

* 2.5.0 (2.202108310208);

**Affected Platforms:**

* Mac OS 10.15;
* Android 10;

**Prerequisites:**

* Have one FxA account with subscription for Mozilla VPN;
* Have the VPN installed and opened on your machine;

**Steps to reproduce:**
1. Go to Settings-> What’s new;
2.  Observe the listed features;

**Expected result:**

* “In-app support form” feature is listed;

**Actual result:**

* “In-app support form” feature is not listed;

**Notes:**

* the "Contact us" option is available in Get Help menu;
* the feature is displayed in "What's new" component if the "unauthSupport" option it is toggled in the Developer options -> Features List;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-918)

**Comment by flozia** [comment]
I think this is the expected behaviour and not a bug. We show only features that are new, supported and enabled in the _What’s new_ tour. The _In-app support form_ will be listed as a feature as soon _In app support_ #1341 is enabled.

Until then enabling it in the Developer options is a good way to still test this. In case there are anymore related open questions or issues feel free to reopen.
