### ISSUE TITLE
Popup system notifications regarding VPN app, are missing on android

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#181]

**Comment by jess-cook03** [comment]
@strseb @bakulf 
This is a system notification -- correct?
That being said what design spec are we looking for? 
A mock up of what a standard Android system notification would look like with the vpn logo and such can be found in this figma file that I just came across inside the Android project ---> [link here.](https://www.figma.com/file/nFQeKRy1hg1NQJIYX4WJeZ/Notifications?node-id=0%3A1)
Take a look at this file and let me know if this works.
 
I would say follow the Android standards as far as technical specs/sizes/behavior etc. -- I think the only UI design guidance to provide here is: 

- [ ] 1) making sure we using the correct VPN app icon: legacy icon or round icon -- either of these should work -- if you need me to export the svg. I can otherwise the link to figma android icons is [here](https://www.figma.com/file/k0BU7oV7R1dUuQgXIzxb3s/Android-Adaptive-Icon-Template?node-id=0%3A1) 👈

**Comment by ValentinaPC** [comment]
Verified this on Android 10 using the latest VPN cross-plat build.
The notifications are listed correctly but the popup function does not work. Expected, @strseb ?
You must check them in the system notifications.
Below is a video with the example.
![ezgif com-video-to-gif(5)](https://user-images.githubusercontent.com/15685960/100870487-5b3f7400-34a7-11eb-8280-f91cedcb4da8.gif)

**Comment by strseb** [comment]
Yes this is expected, on android we should have the icon in the notification bar and a full notification when you open the notification menu :)

**Comment by ValentinaPC** [comment]
Based on the above comment we can mark this as verified-fixed.
