### ISSUE TITLE
Users are not seeing blue banner to update VPN

### ISSUE THREAD

**Issue by JKingZapata** [mozilla-mobile/mozilla-vpn-client#1864]
Users do not update their VPN from 2.4 to version 2.5 as they do not see a banner asking them to update. They are unaware that there might be a new version

* OS affected: Windows 10, macOS
* VPN version 2.4

**Steps to Reproduce**

1. Have an active subscription
2. Have VPN version 2.4 installed
3. Blue banner should appear asking to update to new version

**Actual Results**
- No banner appears
- Users need to download the VPN again from vpn.mozilla.org to get the latest version

![image](https://user-images.githubusercontent.com/72564534/134380045-52d0f72b-46bf-41df-b52e-9f6b616a3560.png)

[mozillavpn-2021-9-22_1.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/7212253/mozillavpn-2021-9-22_1.txt)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1037)

**Comment by JKingZapata** [comment]
What information should we ask customers that would be helpful?

**Comment by anghelos** [comment]
Also true for 2.3. I only just manually installed the new version after waiting for the GPU usage issue to be fixed for a while.

It would be helpful to indicate the version number in the download page, so that users can at least see if they're running the latest one. A "check for updates" button in the app would also be welcome.
