### ISSUE TITLE
No support for split tunnelling on non-GTK desktop environment

### ISSUE THREAD

**Issue by dannycolin** [mozilla-mobile/mozilla-vpn-client#1869]
STR:

1. Download the latest RPM packages from this github repository (currently 2.6.0)
1. Open Mozilla VPN
1. Go to Network Settings OR Preferences

AB:

There's no settings for split tunneling. The "App Permissions" section doesn't exist.

EB:

There should be a section to configure per applications permissions like mentioned on https://support.mozilla.org/en-US/kb/split-tunneling-use-mozilla-vpn-specific-apps-wind

Additional information:

OS: Fedora 34
Kernel: 5.13.16-200.fc34.x86_64
Window Manager: bspwm
Display Manager: x11

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1039)
┆Reporter: Data Sync

**Comment by strseb** [comment]
Hi! On Linux, it seems 2 requirements must be met for split-tunnel to be available:
- Control groups v1 must be mounted.
- Having as desktop manager either "GNOME","MATE","Unity" or "X-Cinnamon" for this we check XDG_CURRENT_DESKTOP

(Actually, we wanted to have this in the linked article, I will look into it.) 

https://github.com/mozilla-mobile/mozilla-vpn-client/blob/da8e80ab9f3d26ead95451e218fb4687d2a3cee3/src/features/featuresplittunnel.h#L42-L56

**Comment by dannycolin** [comment]
> Control groups v1 must be mounted.

Fedora 34 uses cgroup2
```
 ~ $ grep ^cgroup /etc/mtab
cgroup2 /sys/fs/cgroup cgroup2 rw,seclabel,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot 0 0
```
> Having as desktop manager either "GNOME","MATE","Unity" or "Cinnamon" for this we check XDG_CURRENT_DESKTOP
(Actually, we wanted to have this in the linked article, I will look into it.)

No, I only use a window manager (bspwm). What's the reason to limit split tunneling to a specific DE? I still run the same network stack (networkmanager) as Gnome does so technically my setup should be able to support this feature.

Also, since I don't use a DE, `$XDG_CURRENT_DESKTOP` isn't configured. AFAIK, the Freedesktop spec mentions that you should default to an hardcoded path in that case. IIRC, default paths are:
```
/usr/share/applications/
/usr/local/share/applications/
~/.local/share/applications/
```

**Comment by oskirby** [comment]
The reason that this feature depends on a specific DE is that it's difficult to define exactly what an "application" is in the context of a Linux system. We are hooking into the application launch events from the GTK framework to associate a process ID with a a freedesktop application startup file. Once we known the process ID, we can use cgroups to handle all the routing necessary for split tunnelling.

There are some simple things that we can do to enable split-tunnelling on systems with non-GTK environments:
1. We could listen for X-Windows [startup notification protocol](https://specifications.freedesktop.org/startup-notification-spec/startup-notification-latest.txt) to connect an application with a PID. I had a patch for this at some point, but only KDE seemed to report the process ID necessary for this to work.
2. We could provide a wrapper script that allows a user to launch an application from a terminal and place it in within a split tunnel. Similar to what Mullvad offers with their `mullvad-exclude` CLI tool.
3. We can provide CLI tools to place specific PID's within a split tunnel after they have started. This tends to fall apart when trying to isolate applications that do a lot of forking (eg: Chrome).
4. We can identify an application by the executable that was started by looking at the `/proc/<pid>/exe` and `/proc/<pid>/cmdline` but this also falls apart when starting applications via a script.

Another approach would be to make use of cgroups v2, which most DE's are already using to group application processes together, but there doesn't appear to be any good standardization on how cgroups v2 is used and how they correlated to a desktop startup file, so this might require a unique implementation for every DE.

**Comment by dannycolin** [comment]
@oskirby The option 2 would cover my user case. Since we don't have a browser compagnion app yet, I wanted a way to watch Amazon Prime and Netflix without turning off my VPN globally. It also seems to be the easiest and fastest solution to implement according to the information you provided.

**Comment by oskirby** [comment]
Hey @Cimbali Sure, the work that handled X startup notifications is extremely stale, but it was a part of my initial attempt to add split tunnelling to Linux in an abandoned PR #996. During my testing of that work, I found that KDE was the only desktop environment that it actually worked on and we opted not to include it in the final work. The relevant patches probably include:
- fc58e1ae703f06aeee1d3c3d28cd88576ff5e72b: Add the `StartupNotifyWatcher` class to track startup events.
- bbdfc419cffca136f0b5b216899aa03558d80be0: Untangle UID permissions and some testing on Debian with KDE.

During the last round of changes to split tunnelling, we did a bit of refactoring to rely a little more heavily on cgroupsv2 for application tracking since that seems to be getting a lot more mature, and we don't rely on monitoring the process tree with the `PidTracker` class anymore (oops, I see the sources for it are still in the codebase). We still use the launch events as a way to connect an application identifier with a control group, so there may still be some utility in extending this support to include the X startup notification protocol though.

Another avenue you might want to look into if you are motivated, is to look at adding some code to `AppTracker::appHeuristicMatch()` for your desktop environment. This method is called whenever a new control group is created, and if we are able to somehow match that control group with an application ID, then we can do split tunnelling on that control group. There is a TODO comment in that function that speaks to how we could make this work without an explicit PID or application launch event.

**Comment by Cimbali** [comment]
For the record, most cgroup patterns seem to be all be prefixed with `app-` and postfixed either with `-hex[0-9a-f]{32}.scope` (meaning a 32-character hex string), or `@autostart.service`. My system currently runs **KDE’s plasma 5 desktop 5.26.4-1.1**.

The remaining middle bit can either be:
- a desktop id: `org.kde.kgpg`, `org.kde.dolphin`, `firefox`, `geoclue\x2ddemo\x2dagent` (most cases)
- a full app name (capitalised and all): `Proton\x20Mail\x20Bridge`, `Signal\x20Private\x20Messenger`, `Zoom`
- the terminal command used to start the app, e.g. “konsole” (which could be matched against Exec= fields in desktop files) or \x2ftmp\x2flaunch.sh (meaning scripts will break this matching)

Note that some characters are hex-encoded so `\x20` for ` `, `\x2d` for `-`. My system currently runs KDE’s plasma 5 desktop 5.26.4-1.1.

In also noted trying out various apps I found some exceptions:
- Apps started directly from a terminal seem to just use the cgroup of the terminal. By directly I mean e.g. `okular file.pdf` instead of `xdg-open file.pdf`
- Gnome terminal created its own slice, with /app-{desktop id}.slice/ and under that a “server” cgroup and an additional cgroup per vte.
- MS teams uses the cgroup /user.slice/user-1000.slice/user@1000.service/session.slice/plasma-plasmashell.service − I don’t see anything in the desktop file to let us infer that
- Then there some remaning cgroups that are not prefixed with `app-`, but I think these are not linked to desktop files:
   ```
   xdg-permission-store.service
   evolution-calendar-factory.service
   xdg-desktop-portal-gnome.service
   dconf.service
   dbus.socket
   evolution-source-registry.service
   xdg-desktop-portal-gtk.service
   ```

**Comment by Cimbali** [comment]
To be fair if we get the pid, I think the most reliable way of connecting it back up to cgroups is to use `/proc/pid/cgroup`.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

We believe this has been fixed.
Closed during bug squashing.
