### ISSUE TITLE
How should notifications on mobile be implemented? 

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#222]

**Comment by jess-cook03** [comment]
@jess-cook03 system notifications iOS + android

**Comment by jess-cook03** [comment]
@lesleyjanenorton I'm going to link this issue with #181

I provided a link to a figma file I had came across that has Android system notifications mocked up for VPN... that should be covered.

For iOS there is also a file[ link here](https://www.figma.com/file/kV7W34ppOrkuw6tbXnAojL/Notifications?node-id=6%3A96)
- This file is definitely can be built out more right now **if we identify some critical states that we need for 2.0** .... I think it would be helpful to understand all the gaps of notifications that we don't have treatment for or aren't sure how to treat (out of the bounds of iOS standard specs or require us to provide more on our end).
--- Otherwise just following the iOS technical standard specs - we only really need to replace icons at certain stages...

One case is the transparency with two ctas -- again following iOS treatment but wanted to document that instance here:
![IMG_4909.PNG](https://images.zenhubusercontent.com/5fa9aeffe066e101cbf88509/30989d85-40a1-49f9-8f1f-93e4cf77e9f0)

Feel free to ping me on this or if we need to jump on a call I'm happy to!

**Comment by jess-cook03** [comment]
@lesleyjanenorton @chrismore 
Confirming/sign off that we are all set with these notifications?

**Comment by chrismore** [comment]
@ValentinaPC this is now done. Can you verify this is QA verified and then close this issue? Thanks!

**Comment by ValentinaPC** [comment]
We can close this one, based on the verification from https://github.com/mozilla-mobile/mozilla-vpn-client/issues/181.
If anything else should be checked here, please let us know.
