### ISSUE TITLE
Captive Portal updates

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#224]
1.) When captive portal is detected, we need to notify the user and ask them to disconnect the VPN. We need to know what this notification should say, and what it should look like.

2.) Once the VPN has been disconnected and captive portal is still detected, which view should the user see? 

Resources
https://developer.apple.com/design/human-interface-guidelines/macos/system-capabilities/notifications/

**Comment by jess-cook03** [comment]
@jess-cook03 to create mini flow for this messaging for this.... need to show that user is disconnected from VPN and connected to captive portal now.

Document further here.

**Comment by jess-cook03** [comment]
**Proposed project plan**
Copied from original zenhub ticket...

_Goal_
Due to legal constraints, VPN users will need to acknowledge that a captive portal has been detected and that they wish to disconnect from the VPN (so that they can resolve the captive portal). After they resolve it, the VPN client can automatically detect that and reconnect by itself.

@malqinneh to continue wrapping up the work on this item by end of week.

**Comment by malqinneh** [comment]
cc @chrismore @bakulf @lesleyjanenorton 

Based on recent conversation, we are legally obligated to acknowledge with users that in order to use a WiFi hotspot with a captive portal, they need to manually disconnect the VPN. I have a quick flow/illustration on how we might handle this via Mac OS below:

![image.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/3bcf5176-9660-4bf7-bec4-0b272f0d046d)

1. VPN app detects captive portal
2. VPN app asks user to disconnect before they can use WiFi hotspot
3. If user disconnects via app notification action, VPN app redirects users to captive portal login page
4. When user successfully bypasses captive portal login page, VPN app automatically reconnects (with push notification)

*Think* this could work similarly on mobile as well.

I've updated the notifications copy to reflect the above:

![Mac OS - Notification.jpg](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/cf7f7fa6-3448-4800-98e2-a65b7bf5373c)

**Comment by bakulf** [comment]
The main issue I see on using the notifications is that it will be available on macOS/iOS only.

On macOS/iOS, apple offers the 'alert' notifications:
https://developer.apple.com/design/human-interface-guidelines/macos/system-capabilities/notifications/

but this is not available on linux, windows or on android. I would prefer to have something cross-platform.
Here is an idea, let me know if it works:

1. we show a normal notification (maybe on Mac we can use alerts)
2. clicking on the notification, we open the MozillaVPN app and in there, we show modal dialog.
3. the dialog can look like the removal device confirmation dialog.
4. In there, the user has to choose to disable the VPN tunnel or to keep it in the current status.

**Comment by malqinneh** [comment]
@bakulf we can use [alert notifications in iOS](https://developer.apple.com/design/human-interface-guidelines/ios/system-capabilities/notifications/) as well.

Think there are also actionable alert notifications on Windows. Did not look at Linux yet. This may pose a problem if we can't support alert notifications on Linux.

Your proposal makes sense to keep one consistent solution across all platforms. Will iterate on this and report back here by EOD.

**Comment by malqinneh** [comment]
Spoke with @jess-cook03 after the UX team meeting this morning, we will need to speak with @bakulf to understand the back-end implementation and its influence on front-end before we move forward and iterate. Planning to schedule this sync for when we're back (week of Nov 30-Dec 4).
