### ISSUE TITLE
update android app id

### ISSUE THREAD

**Issue by bhearsum** [mozilla-mobile/mozilla-vpn-client#266]
Android is currently being built with `com.mozilla.vpn` as the appid. The previous version of MozillaVPN was built with `org.mozilla.firefox.vpn`. If we want to be able to upgrade the older users to the new version we must build with the same appid.

**Comment by chrismore** [comment]
Good catch @bhearsum. I assume that the "firefox" portion of the ID was removed due to the product no longer being branded as "Firefox". When we launched 1.0 as "Mozilla VPN" we kept this same ID so that legacy users get upgraded and that they aren't considered two separate apps.

@bakulf can we update this so there is a natural upgrade path for legacy v1.x clients?

**Comment by ValentinaPC** [comment]
Verified as fixed on Android 10, using the cross-plat v.2.0.0 (12/04/2020) VPN build.
The Mozilla VPN app id is: org.mozilla.firefox.vpn.
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/101357097-aab7e280-38a1-11eb-9a04-993fc919eec2.png)
