### ISSUE TITLE
Considering the renaming of 'preferences' to 'settings'

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#289]

**Comment by ValentinaPC** [comment]
As a side note: we do not have a "Settings" screen title inside the VPN app cross-plat build when in MacOS.
Suggestions:
- we could change the "Preferences..." option from the VPN menubar into "Settings" so that Windows users know what is about;
- we could add a "Preferences" title to the settings screen while using macOS;
- we can leave it like it is;

**Comment by jess-cook03** [comment]
Capturing as design feedback/suggestions and documenting elsewhere in backlog for future design iterations. Closing issue.
