### ISSUE TITLE
[macOS] String IDS systray.hide and help.helpCenter displayed instead of translations

### ISSUE THREAD

**Issue by flodolo** [mozilla-mobile/mozilla-vpn-client#306]
Latest build available `2.202011261414`. I have no way to tell if it's just a problem of the submodule not being updated. If that's the issue, it would be good to have it updated as part of the build process.

<img width="395" alt="Schermata 2020-11-26 alle 15 51 37" src="https://user-images.githubusercontent.com/3644868/100419302-98a99900-3084-11eb-945a-6bbb2fd3ed5b.png">
<img width="472" alt="Schermata 2020-11-26 alle 15 51 06" src="https://user-images.githubusercontent.com/3644868/100419313-99dac600-3084-11eb-97e6-51779e795350.png">

**Comment by flodolo** [comment]
@bakulf 
It would be nice to explain why it was closed ;-)

**Comment by bakulf** [comment]
ah! yes, because I fixed the issue in the last build. The tree was not updated when I made the builds.
Next step is to force an update each time a build is created.
In commit https://github.com/mozilla-mobile/mozilla-vpn-client/commit/0593e5da35844dd6f322f398c1ee843cbc5184b5 I also forced the translation of the menubar and the context menu when the language is changed.

**Comment by ValentinaPC** [comment]
Verified as fixed on Mac OS 10.15.6, using the VPN cross-plat build v. 202030111338.
Postfix screenshots below.
![image](https://user-images.githubusercontent.com/15685960/100871655-4b289400-34a9-11eb-84a1-ef545fc6a972.png)
![image](https://user-images.githubusercontent.com/15685960/100871691-58de1980-34a9-11eb-9a95-1f6e89080a0e.png)
