### ISSUE TITLE
Provide QA a way to test hard to trigger authentication errors

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#3232]
Add inspector commands to trigger authentication errors so that QA can check UI.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2017)

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

The list of hard-to-reproduce auth errors are:

email type not supported

  * errno: 142
  * This happens if you try to log in with a secondary email
  * Easy to reproduce

account already exists

  * errno: 101
  * This could reproduced trying to create a second account with the same email address. You need 2 devices.
  * Maybe this can be reproduce.

email already exists

  * errno: 144
  * We do not support adding a second email address. This cannot be reproduced.
  * Ignore it

email cannot be used to login

  * errno: 149
  * FxA can add a flag to the DB to disable accounts. Impossible to reproduce it.
  * Ignore it

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this on Mozilla VPN 2.8.0 (16487490), while on Android and on Mozilla Mozilla VPN 2.8.0 (2.202203311526), while on iOS.

We were able to verify the email type not supported error. While signing in with a secondary email, a “Sign-in failed” modal is displayed (attaching a screenshot);

Regarding the second authentication error - account already exists, we were not able to trigger this error. When signing in on a 2nd device with the same email address, the user is redirected to the account creation flow and is asked to enter the password for his account;

!1648798909413.JPEG|width=945,height=2048!
