### ISSUE TITLE
Glean event recording error for `sample.connectivity_stable`

### ISSUE THREAD

**Issue by badboy** [mozilla-mobile/mozilla-vpn-client#3372]
We're seeing a sharp increase in Invalid Value errors for the `sample.connectivity_stable` event since April 18.

The [event metric definition](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/058cfd630b2c8c6d6d1ed5ffc4a0b359a3393f2d/glean/metrics.yaml#L792-L812) only lists the `server` extra key,
but [the recoording code](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/058cfd630b2c8c6d6d1ed5ffc4a0b359a3393f2d/src/telemetry.cpp#L62-L69) passes in 3 more values.

You will need to define the other extra keys as well.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2123)
┆author: Data Sync

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Thank you so much for the report and figuring out the problem! We’ll get this updated for our next release.

**Comment by birdsarah** [comment]
@bakulf this is also an issue for authentication_inapp_error and possible restarted.

We should include all fixes for this fix.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

As of Mozilla VPN v2.5, QA was informed that Adjust testing will be covered entirely by automated tests. Based on this fact, our suites do not contain any Adjust checks.

Action item: Add few manual tests for Adjust, in order to avoid this type of issues in the future;

Please let us know if we should do this. Thank you!

Madalin Cotetiu Rebecca Billings Betty Fleming Sarah Bird Adrienne Davenport

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Andrea Marchesini Is there a way to catch this using manual tests? if not, could we implement a way? Thanks!
