### ISSUE TITLE
[Android] Button press activation behaviour should not trigger when finger left

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/mozilla-vpn-client#3384]
1. Press and hold any button
2. Decide to cancel the action, leave button area with finger
3. Release finger from screen

Expected: per convention, do not activate button

Actual: button becomes activated despite not releasing the finger on the button.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2130)
┆author: Data Sync

**Comment by lesleyjanenorton** [comment]
Also happens on desktop. We should fix.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this as fixed on the latest 2.10 builds, while using Android 10, iOS 14 and MacOS 11.6.

The buttons are no longer activated when leaving button area with finger/mouse cursor.

On Windows are not able to verify this issue, due to the following one: https://mozilla-hub.atlassian.net/browse/VPN-2631 ( https://mozilla-hub.atlassian.net/browse/VPN-2631|smart-link )  

Attaching postfix video.

!original-9940ADB8-1B8D-43B8-9D62-41D16F492C29.mp4|width=444,height=960!

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Also, verified this as fixed on Mozilla VPN 2.10.0 (2.202208050620), while using Windows 11.
