### ISSUE TITLE
[Android] Authentication screen is never loaded on Android devices 5.1 or 6 

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/mozilla-vpn-client#344]
Trying to test issue #180 I downloaded and installed emulator for Android 5.1 and 6, API 22. 
In both cases after clicking on Get started button the Authentication screen is shown but never loaded correctly. See screenshot:
![Screenshot_1606917309](https://user-images.githubusercontent.com/1897507/100881839-b6c13000-34ae-11eb-95ea-e4d481bdb8ad.png)

On other emulators, Android 9.0 API 28, the app works fine. It still may be an issue with emulator, but worth filing it just in case there is a real issue.
If there are any logs that helps, let me know and I will share here. 

The apk used was shared by @ValentinaPC

**Comment by bakulf** [comment]
@tduzan do we want to support android 6?

**Comment by strseb** [comment]
That is an interesting one! - On my Android 6 Emulator we're getting a js syntax error. 
This is caused by the pretty old webview we're having here. For me it's chrome 44 (from 2015) 
Since [Android 5 the Webview should be auto updated by Google Play](https://developer.chrome.com/docs/multidevice/webview/overview/) - Which is not present on 5.0/6.0 emulators. On my Android 7.0 emulator (which has playstore) - only after installing the playstore updates auth is working. 

@chrismore - are we planning to release outside of google play (fdroid etc)? If not, it's very unlikely that users are going to encounter this. - So it's probably more an emulator only issue.

**Comment by bakulf** [comment]
This is good to know! If it's a JS error (@strseb  can you tell me more about it?), we should talk with the FxA team and ask them to fix it.

**Comment by bakulf** [comment]
https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/fxa-dev-process#browser-support
Officially, FxA supports the latest chrome version only.
