### ISSUE TITLE
Unable to complete VPN update to 2.8.3

### ISSUE THREAD

**Issue by JKingZapata** [mozilla-mobile/mozilla-vpn-client#3570]
**Description**

Users on Windows 10 are being prompted to update to new version 2.8.3 but when clicking on the update banner the download does not complete and the VPN app freezes becoming unusable. 

**Technical Information**

Platform Windows 10
FX product Mozilla VPN 2.7.1

**Steps to Reproduce**
1. Have VPN 2.7.1 installed
2. Click on Update Now pop-up
3 Click Yes to authorize msi file installation 

**Actual Results**
- Click Update Now 
- Click yes to authorize msi file installation 
- Windows installer stops mid-way and app freezes

**Expected Results**
- Windows installer should complete update

[2.7.1 no update.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/8730780/2.7.1.no.update.txt)

https://user-images.githubusercontent.com/72564534/169336950-2dd315d2-e55e-4bae-b087-b58b5ba8c27b.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2252)

**Comment by data-sync-user** [comment]
➤ Juan Zapata commented:

We are able to work around this by downloading a fresh install from VPN website

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Can we get logs? Juan Zapata

**Comment by data-sync-user** [comment]
➤ Juan Zapata commented:

Sarah Bird here are the logs

[^2.7.1 no update.txt]

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

This is a bug in v2.7. It has already been fixed in v2.8 but because the installation is handled by the previous version, there is nothing we can do to mitigate the issue.

More in detail, the bug is in the taskscheduler:

  * if the VPN was active or if there is an activate/deactivate task in the queue, the client deletes all the other tasks to complete the operation. Even the TaskRelease is deleted and the MSI execution is killed.

This issue is fixed by installing 2.8 manually.

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Since 2.8 we make some tasks not cancelable. `TaskRelease` is one of them.

**Comment by data-sync-user** [comment]
➤ Ted Campbell commented:

I got stuck on this issue and restarting my computer was enough to get the background service back into a normal state and the update flow started to work again.
