### ISSUE TITLE
[foxfooding] No warning for "This server location is temporarily unavailable. Choose a new location" error

### ISSUE THREAD

**Issue by pdehaan** [mozilla-mobile/mozilla-vpn-client#3695]
No warning for "This server location is temporarily unavailable. Choose a new location" error

At some point during the day the VPN server dropped it's connection and since then I didn't receive an error dialog at all. Also the menu icon doesn't show an overlay to indicate that something is wrong with the VPN connection. Maybe a red cross overlay might be good, and if VPN is disabled the whole icon could be faded out. The current small check mark for an active connection can easily be missed.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2368)

**Comment by data-sync-user** [comment]
➤ Peter deHaan commented:

Row 36 in https://docs.google.com/spreadsheets/d/1nnhaCKuosXdIRtimbS6SwMvt-SqMWwTsjLoFnBKugO4/edit#gid=0 ( https://docs.google.com/spreadsheets/d/1nnhaCKuosXdIRtimbS6SwMvt-SqMWwTsjLoFnBKugO4/edit#gid=0|smart-link )

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Peter Benvenuto re: connection messaging

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Santiago Andrigo can you follow up to get more detail on this issue and perhaps prioritize it further?

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

This seems to have improved quite a bit since this submission. We’ve added status indicators to the traybar icon (https://mozilla-hub.atlassian.net/browse/VPN-2520 ( https://mozilla-hub.atlassian.net/browse/VPN-2520|smart-link )) and I’ve verified that as soon as connectivity is lost, we are indeed showing the ‘in progress' animation. After a while, we give up and we show the OS notification.

!image-20221215-222806.png|width=399,height=157!

Henrik Skupin Please let us know if you think that’s the case!
