### ISSUE TITLE
[Android] Production build has a "beta" build icon

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#384]
#### Affected versions:
- last Android production build;

#### Affected Platforms:
- Android 10;

#### Prerequisites:
- Have the VPN app installed;

#### Steps to reproduce:
1. Observe VPN app shortcut icon;

#### Expected result:
-  Icon has no “beta” label as is the prod VPN app installed.

#### Actual result:
- Icon has a “beta” label.

#### Notes:
- The authentication flow is correct and redirects to fxa production.

**Comment by strseb** [comment]
This is expected :) - Currently our "prod" build on drive is bundled like a beta apk, because we don't need to sign those. Since the bundler then thinks its a "beta" build it attaches the beta-icon and sets a beta package name. 
When using the android_script and inspecting the release-ready apk the right icon is chosen.  
![image](https://user-images.githubusercontent.com/9611612/101916634-81f85b80-3bc7-11eb-960f-146faf7b10bd.png)

**Comment by ValentinaPC** [comment]
@strseb this is not going to happen when we will release the prod build, as I understand, yes?
Thanks!
