### ISSUE TITLE
Show the correct subscription plan intervals.

### ISSUE THREAD

**Issue by flozia** [mozilla-mobile/mozilla-vpn-client#3848]
In addition to `interval_count` we need `interval` from the subscriptions plan to determine the correct plan period.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2456)

**Comment by data-sync-user** [comment]
➤ Florian Zia commented:

The status of this issue was not correctly updated with the corresponding Github issue. It’s also a duplicate of https://mozilla-hub.atlassian.net/jira/software/c/projects/VPN/boards/344?modal=detail&selectedIssue=VPN-2459 ( https://mozilla-hub.atlassian.net/jira/software/c/projects/VPN/boards/344?modal=detail&selectedIssue=VPN-2459|smart-link ) — making as “done”.
