### ISSUE TITLE
IPv6 can be edited with Voice Control while VPN is connected

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#404]
#### Affected Platforms:
- macOS 10.15.7;
 
#### Prerequisites:
- Have the VPN app installed;
- Have a FxA account;
- Have Voice Control enabled;
 
#### Steps to reproduce:
1. Launch VPN app;
2. Connect VPN to any server;
3. Using Voice Control navigate to Network settings;
4. Check/Uncheck IPv6 using voice control;
 
#### Expected result:
- No action is taken because VPN must be turned off to edit this option.
 
#### Actual result:
- IPv6 can be checked/unchecked without VPN being turned off. 
 
#### Notes:
- Not reproducing on the old VPN Windows client;
![IPv6](https://user-images.githubusercontent.com/15685960/103203219-1fa89600-48fd-11eb-81e3-6f231a4344fc.gif)

**Comment by ValentinaPC** [comment]
Verified this on the latest VPN pkg for Mac OS and the issue is still reproducible.
Reopening.

**Comment by chrismore** [comment]
@ValentinaPC would this be considered a **major** issue? The IPv6 setting first won't be likely used among the majority of current target customers and then likely the majority of people who use it, will probably tap the screen vs use voice control to toggle on/off. Even if they do use it with voice and it allows it to be turned on/off, it still won't prevent use of the VPN, because they can still just manually toggle the VPN off/on to make the VPN functional now with IPv6. This seems more like a minor accessibility issue that we should surely fix and make sure other aspects of the VPN function similarly. What do you think?

**Comment by ValentinaPC** [comment]
@chrismore Yes, I think you are right. Beside what you said, I'll add the fact that no so many users use the voice control feature. We can change the issue status to "normal".

**Comment by chrismore** [comment]
yeah, I think "normal" makes more sense. thank you!

**Comment by ValentinaPC** [comment]
Verified this as fixed on the latest VPN pkg for Mac OS 10.15.7 .
Attaching postfix video.
![Voice control](https://user-images.githubusercontent.com/15685960/105323851-52c80780-5bd3-11eb-8d3a-2d88685b2aed.gif)
