### ISSUE TITLE
Windows: CLI output not showing up in PowerShell and Terminal

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#4149]
**Issue**: When attempting to run the CLI version on either Powershell or the Terminal, I’m not getting any output. Baku was able to reproduce as well.

**Steps to reproduce**: 

1. Install the client
1. Open the Powershell and cd into Program Files/Mozilla/Mozilla VPN
1. Run any of the following commands
  1. .\MozillaVPN.exe -h
  1. .\MozillaVPN.exe --help
  1. .\MozillaVPN.exe -v
  1. .\MozillaVPN.exe --version
  1. .\MozillaVPN.exe status

(Screenshot attached).

**Extra:** The client does wake up to ./MozillaVPN.exe so it seems that what’s happening is some terminal output suppression.

**Environment**: Windows 11, client version 2.9.0 (2.202207211137)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2656)
┆Reporter: Santiago Andrigo

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Josh Schrader is this a s/m/l or large?

**Comment by doubouil** [comment]
I tried it as well on my environment : Windows 10 / 2.11.0 (2.202211100715)

I don't have any output but more importantly It seems some command don't do anything, but that's a UI lie : 

`PS C:\WINDOWS\system32>  &'C:\Program Files\Mozilla\Mozilla VPN\Mozilla VPN.exe' activate`

- Does not output anything. 
- Does not launch the app.
- If app is launched and opened, does not refresh status in window or tray icon
- Browsing mullvad.net will show me connected to one of their server as expected

If I close the app and re-open it, It says I'm connected since X seconds corresponding to when I used the command.

`PS C:\WINDOWS\system32>  &'C:\Program Files\Mozilla\Mozilla VPN\Mozilla VPN.exe' deactivate`

- Does not output anything. 
- Does not launch the app.
- Will deactivate the VPN, the UI shows it instantly as if I toggled it off
- Browsing mullvad.net will show me disconnected to one of their server as expected

Here's where things got weird 

`PS C:\WINDOWS\system32>  &'C:\Program Files\Mozilla\Mozilla VPN\Mozilla VPN.exe' select select fr8-wireguard` (checked on [mullvad](https://mullvad.net/en/servers/) as online and well)

Did not output anything as expected. I remembered the [doc](https://github.com/mozilla-mobile/mozilla-vpn-client/wiki/Command-line-interface#server-list) and that you might have needed to deactivate before selecting. I did not check the app since I assumed it had not been refreshed.

```PS C:\WINDOWS\system32>  &'C:\Program Files\Mozilla\Mozilla VPN\Mozilla VPN.exe' deactivate
PS C:\WINDOWS\system32>  &'C:\Program Files\Mozilla\Mozilla VPN\Mozilla VPN.exe' select select fr8-wireguard
PS C:\WINDOWS\system32>  &'C:\Program Files\Mozilla\Mozilla VPN\Mozilla VPN.exe' activate```

The app got refreshed and I could see I'm connected, but checking on mullvad.net shows me a different server than fr8-wireguard, something "close" like fr11-wireguard.

I tried multiple times to deactivate/select/reactivate and got 3 behaviours :

- Connected as expected, app is not refreshed, mullvad shows me a different server than selected (50%)
- Connected as expected, app is refreshed, mullvad shows me a different server than selected (45%)
- Connected as expected, app is refreshed, mullvad shows me the correct server I selected (5%)

Using the app to select a server seems to work 100% and I get the correct city when I specify it.

Hope this helps !

**Comment by data-sync-user** [comment]
➤ Vinoo Cherian commented:

This bug occurs because the VPN app is a Windows GUI app that is writing to console (stdout) when run from CLI.  A Windows GUI app cannot write to console. Only a console app can do that. For example, see CommandLineParser::showHelp which writes to stdout when called with -h command line args.

A solution is to show GUI with the command's results when run with command line args like h etc. Implementing that would be tasklevel work.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Basti How many points would you guesstimate this to be?

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Basti Is this on 2.22?

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this while on Windows 10, using latest Mozilla VPN 2.22 build.

All commands mentioned above, work as expected while run from Terminal/cmd/PowerShell.

Postfix ss below.

!image-20240411-083825.png|width=958,height=428,alt="image-20240411-083825.png"!

!image-20240411-083939.png|width=636,height=89,alt="image-20240411-083939.png"!
