### ISSUE TITLE
RPM Packaging for openSUSE (build without internet)

### ISSUE THREAD

**Issue by guoyunhe** [mozilla-mobile/mozilla-vpn-client#5103]
I am trying to package RPM for openSUSE Linux distros. [openSUSE Build Service](https://build.opensuse.org/) is the official platform for packaging. The platform has a limitation: no internet access is allowed during building process. However, mozillavpn must download go modules when run cmake build. Is here any way to get rid of go module downloading?

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-3417)

**Comment by oskirby** [comment]
I apologize for the late reply. I was on PTO when this was filed and I'm afraid I missed it.

We have a similar situation for our Ubuntu builds where the PPA build environment is also run offline. Our workaround is to run the `scripts/linux/script.sh` file with the `--source` argument. This will download and vendor the Rust and Go dependencies and repack the source directory into a tarball that we can then submit to a PPA for building. You might be able to do something similar for openSUSE.

**Comment by Cimbali** [comment]
I have [opensuse builds](https://copr.fedorainfracloud.org/coprs/cimbali/mozillavpn/builds/) on COPR (though some environments, usually ppc, seem to fail to launch properly), but have very limited experience with oBS unfortunately. I understand it is also a versioning system basically, so you can probably reuse my steps:

1. Get the `Sources.zip` attachment from the “Linux Packages” CI on the release commit ([here for 2.13.1](https://github.com/mozilla-mobile/mozilla-vpn-client/actions/runs/4159188715)), this has the vendoring already done
2. Extract `mozillavpn_<version>~<suffix>.orig.tar.gz` and `mozillavpn.spec`
3. Diff my previous release specfile with the new one to get updates
4. Either upload both files as is, or generate source rpm from them and upload that

I do the first step manually since it’s lightweight and there’s manual intervention required at step 3 anyway. But I’m sure it could be automated with the github REST api if you wanted.

**Comment by data-sync-user** [comment]
➤ Naomi Kirby commented:

This would be resolved by the creation of a post-release action to generate a tarball with all the submodules and vendored components in place. We are going to track that work in VPN-5778

This JIRA task should be mirrored onto github at https://github.com/mozilla-mobile/mozilla-vpn-client/issues/8412
