### ISSUE TITLE
Linux build instructions seem out of date

### ISSUE THREAD

**Issue by Cimbali** [mozilla-mobile/mozilla-vpn-client#6151]
**Describe the bug**
I can’t seem to build the VPN because of glean errors. May be linked to #5395 and #5354 even though the error messages are not the same.

**VPN version:**
  Current master d5540c4df

**Affected Platforms:**
  <Please fill this in>

**Prerequisites:**
- clone repo
- ensure all submodules seem up-to-date and happy, e.g. `git pull --recurse-submodules` or `git submodule update --init --recursive`
- get build dependencies

**Steps to reproduce:**
Run steps to build from source listed in README

**Expected result:**
Steps described in README allow to build from source

**Actual result:**

-  `cmake -S . -B build`   fails with
   ```
   CMake Error at qtglean/CMakeLists.txt:148 (message):
   Glean generated files are missing, and the glean_parser was not found.
   
   Please run: python3 ./qtglean/glean_parser_ext/run_glean_parser.py
   ```
- Trying to run `python3 ./qtglean/glean_parser_ext/run_glean_parser.py`   fails with
  ```
  Traceback (most recent call last):
    File "/path/to/mozilla-vpn-client/./qtglean/glean_parser_ext/run_glean_parser.py", line 12, in <module>
      import cpp
    File "/path/to/mozilla-vpn-client/qtglean/glean_parser_ext/cpp.py", line 19, in <module>
      from glean_parser import util
  ModuleNotFoundError: No module named 'glean_parser'
  ```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-4250)

**Comment by oskirby** [comment]
Hey, the culprit here is that you will need to either install, or upgrade the python dependencies in `requirements.txt` in order to provide the `glean_parser` module. Somewhere in the last release cycle we bumped the minimum required version to 5.0.0 which might by why you're seeing this now if you were previously able to build the VPN client.

Give `pip3 install --upgrade -r requirements.txt` a try and see if that gets you unstuck and in the meantime I will go and update the documentation accordingly. Thanks!

**Comment by Cimbali** [comment]
That fixes it! Thanks

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Owen Kirby Should we mark this as Done?

**Comment by data-sync-user** [comment]
➤ Beatriz Rizental Machado commented:

We do say in the docs to activate the conda environment, which has the Python dependencies installed already. In that case, I’d say this is done.
