### ISSUE TITLE
Can not login in staging mode

### ISSUE THREAD

**Issue by Cimbali** [mozilla-mobile/mozilla-vpn-client#6729]
**Describe the bug**
In order to debug the bugs #6371, #6370 I tried to follow the README instructions and setup the staging mode.

**VPN version:**
2.14.0

**Affected Platforms:**
Linux

**Prerequisites:**
None

**Steps to reproduce:**
- Open `Get Help` menu
- Click `Get Help` title 6 times
- Open `Developer Operations`
- Tick staging option
- Restart mozillavpn

**Expected result:**
I am still logged in, or at least can log in again.

**Actual result:**
Log in attempts fail with an “authentification failed” message.

**Additional notes:**
- No messages about the error causing the auth fail in the log file.
- I get successful sign-in notification emails on my email “Your Firefox account was used to sign in”

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-4652)

**Comment by birdsarah** [comment]
Hi @Cimbali. 

Thank you for your report and thank you so much for trying to engage more deeply with your bug reports. 

Unfortunately because staging accounts unlock access to our VPN network we have to limit them to @mozilla.com accounts.
I will update the documentation to be clearer about the purpose of the staging accounts.

Are you building the VPN client locally. If yes, and you have a paid-for account, then you should be able to do all the debugging you need without a staging account. If you think that's not true, please let us know and we'll see what we can clarify.

**Comment by Cimbali** [comment]
I am building from source indeed. It is really the qml debug view I am after. If there is a way to access it without this staging option that would be great.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Closing this as Staging won't accept non-Mozilla corp accounts.
