### ISSUE TITLE
Incorrect edit settings message while device limit is exceeded

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla-mobile/mozilla-vpn-client#751]
**Affected versions:**
- v. 2.1.0;

**Affected platforms**
- Windows 10

**Prerequisites:**
- Have the VPN app installed;
- Have a FxA account with active subscription for Mozilla VPN;
- Connected to VPN using the same FXA account on at least 5 devices;

**Steps to reproduce**
1. Open the VPN on a 6th device.
2. Go to Settings -> Network settings.
3. Check the error message.

**Expected results**
- There is no error message displayed.

**Actual Results**
- “VPN must be off to edit these settings” error message is displayed.

**Additional notes:**
- This issue reproduces also for the “Notifications” section.

![gif2](https://user-images.githubusercontent.com/18114210/112463676-367b4f00-8d6b-11eb-9f21-964ce08f72d4.gif)

**Comment by bakulf** [comment]
We should make the "settings" button unclickable. @lesleyjanenorton can you help here?

**Comment by birdsarah** [comment]
If settings is unclickable, users can't easily get to "get help" if they're confused or something has gone wrong. 

I'm re-opening to just check in on this decision.

**Comment by bakulf** [comment]
@birdsarah, good point!
Alternatively, we can make "Network settings" and "Notifications" unclickable.
@jess-cook03, thoughts?

**Comment by lesleyjanenorton** [comment]
Or what about adding a "Get Help" link to the devices view when the max-device warning is visible?

**Comment by jess-cook03** [comment]
@lesleyjanenorton and I discussed a potential solution that is mocked up here in this [figma](https://www.figma.com/file/EN0R88zGif4SBj2tvpToJ6/Mac?node-id=1%3A7377) link.

**Comment by bakulf** [comment]
The only way the user can see that screen is at the end of the authentication flow because we "try" to add a new device, only during that step.

Based on that, I have a "contro-proposal".  What about if we show view 701 immediately when the user reaches the device-limit?

Here is the idea:
- the user completes the authentication
- there are already 5 devices
- we show view 701
- without removing a device, the user cannot go "back" to the main view (700).

In this view, we can remove the top menu ("my devices 6 of 5) and the "back" button. When the device is removed, we go back to the main view (700). Thoughts?

**Comment by lesleyjanenorton** [comment]
Hey! I really like this idea, particularly because there's nothing the user can do from the main view _but_ go to the devices view. @jess-cook03 and I talked about doing this briefly last week but it's worth revisiting.
This branch https://github.com/mozilla-mobile/mozilla-vpn-client/tree/fix-751-devices adds 'Sign Out' and 'Get Help' links to the bottom of the devices view when `StateDeviceLimit`. I'll open a PR today. It would be totally easy to hide the back button on this screen  and update the main view if we want to restrict the user to this screen until they've removed a device.

**Comment by jess-cook03** [comment]
@lesleyjanenorton @bakulf We just synced on this solution --- how do we all feel about this? Disable the arrow until the user resolves the devices issue. 
![Screen Shot 2021-04-09 at 1 13 12 PM](https://user-images.githubusercontent.com/54991698/114216783-5c8d1b80-9935-11eb-82a3-cde182f57617.png)
