### ISSUE TITLE
Device removed message displayed upon signing out

### ISSUE THREAD

**Issue by rbillings** [mozilla-mobile/mozilla-vpn-client#780]
When I signed out of Mozilla VPN, the app showed a message saying "Signed out and device removed". This message is confusing. Which "device" is be removed? And removed from what?

Found by: cpeterson
Platform: Windows

**Comment by rbillings** [comment]
This applies to all platforms.

**Comment by jess-cook03** [comment]
@rbillings @lesleyjanenorton 
cc @bakulf 
If I remember correctly when users sign out of the device they are using... that device is removed from their device limit list.... is that correct? Or no

**Comment by birdsarah** [comment]
Relatedly: 

Hi, if you sign in with FXA but don't have a subscription. If you then sign out, then the message reads "signed out and device removed." I think technically speaking this may actually be correct because adding a device is a two part process on the guardian side of things. (That's a separate issue we could clean up.) But I'm wondering if the "device removed" part is confusing if you didn't get as far as being authed in and see the list of devices.

**Comment by lesleyjanenorton** [comment]
@birdsarah great point. I would be confused and possibly worried.  
@jess-cook03 that is correct - the device is removed from their list of active devices but the alert doesn't totally convey what is happening.  

Screen shot for reference: 
<img width="378" alt="Screen Shot 2021-04-29 at 9 13 38 AM" src="https://user-images.githubusercontent.com/22355127/116565179-3d95ff80-a8cb-11eb-9ac5-a1f62c1edea4.png">

I think we should:
1.) Change the background color to green - or something other than red. The red, coupled with the "device removed" bit makes me think something unexpected/bad happened.
2.) Change the string based on whether the user has an active subscription to address @birdsarah's call-out or change the string to something generic enough to accommodate both situations. 

Also tagging @bfyee for input.

**Comment by jess-cook03** [comment]
@chrisrooneys lets see what we can update this string to so it makes more sense to users in this context?
@lesleyjanenorton notification color change I agree it should be either green or blue as its not an error, warning or alert.

**Comment by bfyee** [comment]
Why are we telling the user that a device has been removed?  We have a flow for removing a device, which seems like that would be the only time we should message them of this.

**Comment by birdsarah** [comment]
Any time a user signs out of a VPN client, their device is removed from their device list (on guardian and therefore on clients which pull device list from guardian).

**Comment by punster-moz** [comment]
"device" sound a bit alarming for non-techies because it is not clear what device got removed. If it is explicitly stated the VPN virtual device then user may understand that the removed device is associated with the VPN service.

**Comment by bfyee** [comment]
So are we really just telling them that their device has been disconnected from VPN? (as far as they are concerned)

**Comment by birdsarah** [comment]
Discussion came up for #945 to do a better job of informing the user if their device has been disconnected because their device was removed by another device.

**Comment by lesleyjanenorton** [comment]
I like "disconnected"! One thing to note is we use the "remove device" language in a few places. For consistency, should we update these instances to "disconnect"? 
<img width="163" alt="Screen Shot 2021-05-11 at 6 07 30 PM" src="https://user-images.githubusercontent.com/22355127/117895366-ccb7f580-b283-11eb-90c0-5cc25c88aed9.png">
<img width="161" alt="Screen Shot 2021-05-11 at 6 07 06 PM" src="https://user-images.githubusercontent.com/22355127/117895368-cde92280-b283-11eb-8954-14b9bf59b4a0.png">

**Comment by jess-cook03** [comment]
@chrisrooneys @lesleyjanenorton 
cc everyone else in this ticket thread ----

Confirming the use of 'Disconnect' in this instance.... I would caution updating this for the 'Remove a device flow'..... I would argue that in the instance of when you sign out (regardless of what happens technically in the backend)... a user isn't going to think 'my device is removed from my device list' because they likely will come back and sign in again very soon and we don't show them a message that says after log in 'your device has been added!'.... right because we don't need to.
Hopefully you are still able to follow my train of thought here....
So I believe for this message when you sign out saying 'your device has been disconnected' works potentially better because it tells users yup you signed out and are no longer connected with this device temporarily until you sign in again.....

Actually I would wonder.... do we need to show this message at all at when users sign out? (Don't let this block progress for this ticket we can circle back on this) **For now I say lets move forward with disconnect in that message at this moment.**

Furthermore --- I don't think we need to replace 'remove' with 'disconnect' because when we are asking users to remove a device from their account/their device list... disconnect doesn't mean the same as remove... its not as permanent its more temoporary... I think we should keep our remove language the same for now.

**Comment by chrisrooneys** [comment]
@lesleyjanenorton **Thank you** for surfacing those! That's really helpful. I think we should keep "remove device" in those other instances for now, as @jess-cook03 said, because the phrase seems to have a slightly different meaning in that flow.

**Comment by jess-cook03** [comment]
Perfect! I would say for v2.3 we can confirm updated banner message to 'disconnect'

**Comment by ValentinaPC** [comment]
Verified this on all platforms while using the last 2.3 VPN build.
The new message is displayed at signed out.
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/118804410-53d12300-b8ad-11eb-9db2-0b9670bb78c7.png)
