### ISSUE TITLE
Suggest installation improvements to make it easier to open VPN

### ISSUE THREAD

**Issue by rbillings** [mozilla-mobile/mozilla-vpn-client#781]
The installer asked me to "Go to your Applications folder to open up the VPN and start taking control of your online privacy." Why can't the installer launch the VPN app itself? Or at least open the Applications folder in the Finder? I imagine some Mac users won't know what the Applications folder is or how to find it.

Found by: cpeterson

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-125)

**Comment by bakulf** [comment]
The latest version of the installer execs the client at the end of the installation process. We should change the text.
@jess-cook03 can you help here?

**Comment by jess-cook03** [comment]
Tagging @chrisrooneys lets look at this together! 

- [ ] Needs also prioritization determination from team -- I would suggest p2 or p3

**Comment by chrisrooneys** [comment]
@jess-cook03 @bakulf @rbillings thoughts?
Since the mac installer launches the VPN, there's no need to direct users to the Applications folder. VPN's already open at this point. I'd suggest this change to the body text after "Success!" and before "Trouble with...":

_The Mozilla VPN is successfully installed. You're ready to start taking control of your online privacy._

<img width="627" alt="Screen Shot 2021-05-06 at 9 01 00 AM" src="https://user-images.githubusercontent.com/51548136/118160805-6696b400-b3e4-11eb-8a98-e7d80b6c8b82.png">

**Comment by bakulf** [comment]
I agree. We just need to change the strings because now the app is opened automatically.
Let's move this issue to 2.4 because we cannot change the strings now.

**Comment by jess-cook03** [comment]
agreed -- lets update those strings for v2.4
@chrisrooneys can we/should we keep the 'Trouble with install?' part

**Comment by chrisrooneys** [comment]
@jess-cook03 @bakulf yes, keep that part. Just change the text in between "Success!" and "Trouble with...":

_The Mozilla VPN is successfully installed. You're ready to start taking control of your online privacy._

**Comment by jess-cook03** [comment]
@bakulf @lesleyjanenorton 
cc @chrisrooneys 
We have provided an update to the content/copy here and I want to confirm that this will go into v2.4? Yes? No? Thanks!

**Comment by punster-moz** [comment]
Agreed. This issue should go into V2.5

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Closing this as it has already been verified.

Thank you.

Madalin Cotetiu
