### ISSUE TITLE
Deprecate 1.x clients

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#813]
Will require:
- [x] ~Compiling qt for 32-bit also for v2 clients~
- [x] Force update to v1.4
- [ ] Then force update to v2.1

**Comment by bakulf** [comment]
We do not have 32-bit clients for v1. Mihai and I spent a bit of time this morning together to check the 32-bit balrog config, the client versions, and so on. We do compile a 32-bit version of the windows client but we ship only the 64-bit.

Currently, v2.1 is not required, just recommended. And we do not have a minimum required version. So, first of all, we need to set v1.4 as the minimum required version because any previous builds use the v1 authentication flow.

The next step is to set version v2.1 as required.

**Comment by lesleyjanenorton** [comment]
Can we close this?

**Comment by bakulf** [comment]
The minimum version is now 2.0 for all the platforms.

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

This has been reopened by Data Sync but the Github ticket is still closed, as of 07/14 . Changing it back to Done.

Thank you.
