### ISSUE TITLE
Suggest adding ability to notify users of Mullvad outages

### ISSUE THREAD

**Issue by rbillings** [mozilla-mobile/mozilla-vpn-client#833]
Right now users have no way to know when Mullvad is experiencing an outage unless they reach out to support. Suggest adding the ability to warn users of outages either to the website or the client, or perhaps a "status" in SUMO.

**Comment by lesleyjanenorton** [comment]
@birdsarah Is correct. Here is the current message shown to users when there is an outage. I will file an issue for updating it with a link to the (forthcoming) status page since I can't find an issue for this either.
<img width="363" alt="Screen Shot 2021-04-12 at 10 08 02 AM" src="https://user-images.githubusercontent.com/22355127/114417163-f8599a00-9b76-11eb-9724-e3a5e97d4af8.png">

**Comment by bakulf** [comment]
This view is exposed when the app obtains unexpected content when fetching the heartbeat REST endpoint.
This check is done at the beginning of the authentication flow, once per hour, and when there are connection failures.

**Comment by birdsarah** [comment]
https://status.vpn.mozilla.org now exists.
