### ISSUE TITLE
IP leaked while torrenting (MacOS)

### ISSUE THREAD

**Issue by paxperscientiam** [mozilla-mobile/mozilla-vpn-client#873]
Hello! I did some basic prodding and noticed that the VPN is leaks my IP while torrenting. I used this* site and Transmission for my test.

Is this something that will be fixed?

* https://ipleak.net/

Setup:

* macOS 11.2.3
* Mozilla VPN version is 2.1.0 (2.202103261745)

Side note: please make the "Release Version" text selectable!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-138)
┆Reporter: Data Sync

**Comment by bakulf** [comment]
Thanks for this bug report. I filed a separate issue for the version-text selectable (https://github.com/mozilla-mobile/mozilla-vpn-client/issues/874). 

@paxperscientiam, can you tell me more about how to reproduce this ip-leak? Does it happen all the time when using a torrent client?

**Comment by paxperscientiam** [comment]
> Thanks for this bug report. I filed a separate issue for the version-text selectable (#874).

That's quite good of you. Thanks!

Yes, instructions on how to reproduce:
1. Load up https://ipleak.net/
2. Scroll down to "Torrent Address detection" section and click "Activate" (IP addresses in screenshot are as expected since I'm VPN'ing into a Washington server):
![Screen Shot 2021-04-20 at 12 16 10 PM](https://user-images.githubusercontent.com/7539871/115430248-32a7e480-a1d2-11eb-8575-bb69db0b103e.png)
3. Copy the provided magnet link
4. Open it with your favorite torrent app, but be sure to keep https://ipleak.net/ open
5. Head back to the "Torrent Address detection" section of https://ipleak.net/ and check out the results

Interesting thing is that this time the detected IP geolocated to Germany while last night I got my public IP. I'm no expert, so I'm not aware of all the variables that may be at play here.

**Comment by bakulf** [comment]
I wonder if this is a "Firefox" issue when DoH (DNS over HTTP) is enabled. @paxperscientiam can you please try the following:

1. activate the VPN
2. close Firefox entirely
3. open it again and check if the IP address is leaked.

If Firefox uses DoH, it can be that it keeps the same HTTP2 connection to the DoH provider even after the VPN activation. Because of that, any IP resolution will be done "outside" the VPN tunnel. There is not a way to reset the Firefox HTTP2 connection from the VPN client (yet). In Q3 we will work on it, but so far, leaks can happen (note that this should be a common issue even for other VPN projects).

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

This has been hanging around for far too long, and we haven't been able to reproduce it in a meaningful way.
