### ISSUE TITLE
UI/Dock and Menu Bar Icon Issues in macOS Big Sur

### ISSUE THREAD

**Issue by heldentenor** [mozilla-mobile/mozilla-vpn-client#885]
Wanted to raise some UI/icon-related issues for macOS Big Sur, specifically with menu bar and dock icons. Menu bar icon (first screenshot) is larger than default menu bar icon size and pixelated/blurry; dock icon is larger than default icon sizes in Big Sur. 

<img width="257" alt="Screen Shot 2021-04-21 at 9 46 32 AM" src="https://user-images.githubusercontent.com/82953926/115564450-76f4bc80-a286-11eb-86ad-90bf096a5c9b.png">

<img width="233" alt="Screen Shot 2021-04-21 at 9 47 23 AM" src="https://user-images.githubusercontent.com/82953926/115564577-9390f480-a286-11eb-9e30-f02405aac15b.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-140)

**Comment by lesleyjanenorton** [comment]
@heldentenor thank you for filing! Would you mind sharing some details about your device? I'm specifically curious the year and graphics card (these can found by going to the Apple () menu > About this Mac).

**Comment by heldentenor** [comment]
@lesleyjanenorton: Yup! It's a Macbook Air 2020 and the GPU is the M1 chip.

**Comment by lesleyjanenorton** [comment]
@heldentenor thank you!

**Comment by jess-cook03** [comment]
@lesleyjanenorton can you fill me in on specifics you need for this? If i need to create and export assets or not? 
If not feel free to remove UX/UI label please, thanks :)

**Comment by lesleyjanenorton** [comment]
Hey! So I think we'll need a new App Icon asset created in a few different sizes. The App Icon assets we have for macOS follow the sizing specifications provided by Apple but appear much larger than other icons because they don't account for the _outer bounding box_ and _inner bounding box_ described [here](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/). I'm not sure what the fix is - maybe an icon with X pixels transparent padding to make the sizing of the icon look more comparable to other icons? 

The other issue is that the current assets are blurry on 2020 mac devices (may also affect older devices with better graphics cards, idk) so hopefully we can optimize the new assets to stand up better on newer devices.

**Comment by lesleyjanenorton** [comment]
Also some icon inconsistency on Android
![Screenshot_20210430-112510](https://user-images.githubusercontent.com/22355127/116725932-3c86d000-a9a8-11eb-91df-ec3c8f7637ca.png)

**Comment by ValentinaPC** [comment]
Verified the icons on Mac OS 10.15, using the last VPN build (2.202105230622).
- the menu bar icon looks ok while app is closed, but looks bigger while open. (second second screenshot)
- the tray icon has the correct size;
![Untitled](https://user-images.githubusercontent.com/15685960/119346704-3d5b0b00-bca3-11eb-9a6d-00ab5a6a6ab6.png)


If we are ok with the size of the icon **while VPN app is open**, we can close this.
