### ISSUE TITLE
Cannot connect IAP user to FXA user.

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#905]
Related to #904. If an IAP user has a subscription but has forgotten, or potentially deletes, the FXA account associated with the VPN then we have no way of determining their subscription status.

The data the guardian-website receives about an apple purchase contains no identifying information such as the apple id email address associated with the subscription.

Additionally, the receipt that the customer receives from Apple confirming their payment and subscription contains no information or IDs that we can use to join with the transaction confirmation we received from Apple https://developer.apple.com/forums/thread/95326. 

[Companion issue on guardian-website](https://github.com/mozilla-services/guardian-website/issues/1134)

* but fix for this may well be client side not in guardian-website db.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-145)
┆Reporter: Data Sync

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Moritz Birghan is still a valid issue?

**Comment by data-sync-user** [comment]
➤ Moritz Birghan commented:

In the case that the user has forgotten the FxA account, this is still a valid issue. However, we should be able to detect the FxA account when pressing “Restore purchase”. We detect if the purchase is already associated with an account, therefore we should also be able to say which account it is. 

In the case of a deleted account, the user should be able to connect the purchase to a different account using “Retore purchase” since there is no longer an account associated with the receipt.

Sarah Bird does that make sense or did I miss something?

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Moritz Birghan this is right.

**Comment by data-sync-user** [comment]
➤ Moritz Birghan commented:

If the user tries to restore the purchase that is connected to a different account should we say which account it is connected too? 

I can see some privacy concerns but it feels better than to say nothing.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

I do not think we should, no. But that’s really a question for product Brian Yee and maybe legal.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Guardian no longer maintains subscriptions and so this issue is now resolved.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Moving back to Cancelled
