### ISSUE TITLE
⏰ iOS builds must use iOS 17 SDK or later to submit apps starting April 29, 2024 ⏰ 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#9114]
Per Apple, all builds submitted to App Store starting April 29, 2024 need to be on the 17 SDK or later. We’re currently building against the 16.4 SDK, per an email I received from App Store Connect.

{quote}We identified one or more issues with a recent delivery for your app, "Mozilla VPN - Secure & Private" 2.21.0 (3716). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

*ITMS-90725: SDK version issue* - This app was built with the iOS 16.4 SDK. Starting April 29, 2024, all iOS and iPadOS apps must be built with the iOS 17 SDK or later, included in Xcode 15 or later, in order to be uploaded to App Store Connect or submitted for distribution.

After you’ve corrected the issues, you can upload a new binary to App Store Connect.{quote}

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-6194)
┆Reporter: Gela Malek Pour

**Comment by data-sync-user** [comment]
➤ Gela Malek Pour commented:

From Basti:

{quote}This is likely as simple as changing the Xcode version used in our Xcode Cloud builds (and telling all developers to upgrade on their local device), but I’m not 100% sure. We also need to do that on taskcluster then, so we don’t have awkward situations.{quote}

**Comment by afanchamp** [comment]
I'm facing the same issue since last night, before that i was successfully uploading builds to testflight. I'm getting this warning 
"SDK version issue. This app was built with the iOS 16.2 SDK. Starting April 29, 2024, all iOS and iPadOS apps must be built with the iOS 17 SDK or later, included in Xcode 15 or later, in order to be uploaded to App Store Connect or submitted for distribution. " 
I have a Mac Book pro 2021 with Apple M1 Pro chip and my Xcode version is Version 14.2 (14C18) and i don't have any update showing for xcode in Appstore. If anyone can help.

**Comment by donkaprat** [comment]
Me too, I m facing the same problems, My Xcode is a version 15.2 and I use a transporter for push new version. On my application i use Expo and this version sdk is 49. If anyone can help. Thanks so much.

**Comment by Abhishekk63** [comment]
@donkaprat upgrade your app to Expo SDK 50 from 49. 
[link](https://expo.dev/changelog/2024/01-18-sdk-50#%E2%9E%A1%EF%B8%8F-upgrading-your-app)

**Comment by Pranshik18** [comment]
As per the apple requirements, you have to upgrade the project minimum iOS deployment version to v12.0 and also upgrade the xCode to v15.0 or newer. if you are using react-native then also check that the react native version you are using is compatible with iOS 17 SDK. I have solved this issue by upgrading the xCode from v13.2 to v15.2 and also my RN version is 0.72.8.

**Comment by data-sync-user** [comment]
➤ Matt Cleinman commented:

For Xcode Cloud builds, this is a setting in Xcode Cloud (which has been changed for both workflows).
For Taskcluster, https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9185 ( https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9185|smart-link )  will update the version used.

**Comment by Andrey5045** [comment]
2024-05-15 20:33:45.840 *** Error: Asset validation failed SDK version issue. This app was built with the iOS 16.4 SDK. All iOS and iPadOS apps must be built with the iOS 17 SDK or later, included in Xcode 15 or later, in order to be uploaded to App Store Connect or submitted for distribution.

So... what to do?

**Comment by ToolmakerSteve** [comment]
> I do not use X-code, I upload straight to GitHub and compile there by running a task. So... what to do? Any settings?

If you are deploying an iOS app to Apple, then Xcode is running _somewhere_. Look into how/where that task causes xcode to run.

**Comment by vignyl** [comment]
J'ai écris un post sur ce probleme:
https://www.linkedin.com/posts/vignyl-sinclaire-mbounda-tchate-96754915a_publication-dune-application-mobile-sur-activity-7201534313144758272-186x?utm_source=share&utm_medium=member_desktop
