### ISSUE TITLE
Device restart required after a failure

### ISSUE THREAD

**Issue by rbillings** [mozilla-mobile/mozilla-vpn-client#937]
From user feedback: After emulating a scenario in which all MozillaVPN.exe get terminated, the app can be launched again but fails to connect (there was banner about a background service error shown for a split second when the app got launched). A device restart was required to get the connection working again.

platform: Windows 10

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-164)
┆author: Data Sync

**Comment by ValentinaPC** [comment]
We tried to reproduce this on both Windows and Linux platforms, while ending the VPN process (killing it), but we did not managed to.

**Comment by madalincm** [comment]
I was able to trigger to Background service error banner by killing the process from the task manager but I was able to turn the VPN back on without restarting the app or the device.
![backgroundError](https://user-images.githubusercontent.com/15685441/117002373-26e91180-acec-11eb-8f32-aa073594c7b0.gif)

I was not able yet to trigger the banner using other steps.

**Comment by oskirby** [comment]
After thinking about this for a bit, this might be the expected behaviour. There should be multiple instances of `MozillaVPN.exe` running, in addition to the client there should also an instance for the tunnel broker daemon and a third for the wireguard tunnel whenever the VPN is connected.

Abnormal termination of the daemon can leave the VPN non-functional until it's restarted (either by a full reboot, or manually restarting the service from the service manager).

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Owen Kirby is this the expected behavior? What is the final conclusion? Thanks!

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

See the latest Owen Kirby's comment
